presto:
  workers: 2
  service:
    type: NodePort
    port: 8080
  logLevel: INFO
  environment: production
  query:
    maxMemory: 4GB
    maxMemoryPerNode: 1GB
  jvm:
    maxHeapSize: 8G
    gcMethod:
      type: UseG1GC
      g1:
        heapRegionSize: 32M
  deploy:
    replicas: 1
    container:
      image: jeffgrunewald/presto
      tag: '1.1'
      pullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  ingress:
    enable: true

metastore:
  service:
    type: ClusterIP
    port: 9083
  warehouseDir: warehouse
  deploy:
    replicas: 1
    container:
      image: jeffgrunewald/metastore
      tag: '1.0'
      pullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

postgres:
  enable: true
  db:
    name: metastore
    user: hive
    password: password123
  service:
    type: ClusterIP
    port: 5432
  storage:
    persist: false
    size: 5Gi
    mode: ReadWriteOnce
  deploy:
    replicas: 1
    container:
      image: postgres
      tag: 11.1-alpine
      pullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

minio:
  enable: true
  storage:
    mode: ReadWriteOnce
    size: 5Gi
  service:
    type: NodePort
    port: 9000
  deploy:
    replicas: 1
    container:
      image: minio/minio
      tag: RELEASE.2019-01-16T21-44-08Z
      pullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  ingress:
    enable: true

hook:
  container:
    image: alpine
    tag: '3.8'

hive:
  enable: true
  service:
    type: NodePort
    port: 10000
  deploy:
    replicas: 1
    container:
      image: jeffgrunewald/hive
      tag: '1.0'
      pullPolicy:
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  spark:
    container:
      image: jeffgrunewald/spark-2.4-base
      tag: '1.1'
      pullPolicy: IfNotPresent
    master:
      url: https://kubernetes.default.svc.cluster.local:443
    executor:
      instances: 2
      memory: 512m
      labels:
      - key: hadoop-less
        value: 'true'
    driver:
      labels:
      - key: hadoop-less
        value: 'true'
    appName: kdp
    deployMode: cluster

global:
  environment: sandbox
  objectStore:
    bucketName: kdp-cloud-storage
    accessKey: secret-key
    accessSecret: super-secret
