kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coordinator
  labels:
    presto: coordinator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        presto: coordinator
    spec:
      containers:
      - image: starburstdata/presto
        livenessProbe:
          exec:
            command:
            - /etc/init.d/presto status | grep -q 'Running as'
          failureThreshold: 3
          periodSeconds: 300
          timeoutSeconds: 10
        name: presto-coordinator
        ports:
        - containerPort: 8080
      restartPolicy: Always
