---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-server
  labels:
    app: hive-server
spec:
  selector:
    matchLabels:
      app: hive-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hive-server
    spec:
      containers:
      - name: hive-server
        image: jeffgrunewald/hive-server:1.5
        imagePullPolicy: IfNotPresent
        workingDir: /opt/hive
        command:
        - /bin/sh
        - -c
        args:
        - 'cp /tmp/hive-site.xml /opt/hive/conf/ && sed -i "s/POD_IP/${POD_IP//./-}/" /opt/hive/conf/hive-site.xml && ./bin/hiveserver2'
        ports:
        - containerPort: 10000
          name: hive-server
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /tmp/hive-site.xml
          name: hive-site
          subPath: hive-site.xml
      volumes:
      - name: hive-site
        configMap:
          name: hive-site
