name: kubernetes-data-platform
apiVersion: v1
description: Hadoop-less data platform for the Smart City OS
version: 1.0.0
tillerVersion: ">=2.8.0"
keywords:
- presto
- hive-metastore
- cloud-object-store
- minio
sources:
- https://github.com/prestodb/presto
- https://github.com/apache/hive
- https://github.com/minio/minio
- https://github.com/helm/helm
