presto:
  workers: 2
  service:
    type: NodePort
    port: 8080
  logLevel: INFO
  environment: production
  query:
    maxMemory: 1GB
    maxMemoryPerNode: 0.5GB
    maxTotalMemoryPerNode: 0.6GB
    heapHeadroomPerNode: 0.75GB
  jvm:
    maxHeapSize: 1536M # look for environment specific values
    gcMethod:
      type: UseG1GC
      g1:
        heapRegionSize: 32M
  deploy:
    replicas: 1
    container:
      image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/presto
      tag: latest
      pullPolicy: IfNotPresent
      resources:
        limits:
          memory: 2Gi # look for environment specific values
          cpu: 2 # look for environment specific values
        requests:
          memory: 2Gi # look for environment specific values
          cpu: 1 # look for environment specific values
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  ingress:
    enable: true
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /v1/cluster

metastore:
  jvm:
    maxHeapSize: 768M
    gcMethod:
      type: UseG1GC
      g1:
        heapRegionSize: 32M
  allowDropTable: false
  service:
    type: ClusterIP
    port: 9083
  warehouseDir: hive-s3
  deploy:
    replicas: 1
    container:
      image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/metastore
      tag: latest
      pullPolicy: IfNotPresent
      resources:
        limits:
          memory: 1.5Gi
          cpu: 1
        requests:
          memory: 1.5Gi
          cpu: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

postgres:
  enable: true
  db:
    name: metastore
    user: hive
    password: password123
  service:
    type: ClusterIP
    port: 5432
  storage:
    persist: false
    size: 5Gi
    mode: ReadWriteOnce
  deploy:
    replicas: 1
    container:
      image: postgres
      tag: 11.1-alpine
      pullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

minio:
  enable: true
  storage:
    mode: ReadWriteOnce
    size: 5Gi
  service:
    type: NodePort
    port: 9000
  deploy:
    replicas: 1
    container:
      image: minio/minio
      tag: RELEASE.2019-01-16T21-44-08Z
      pullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  ingress:
    enable: true

hook:
  container:
    image: alpine
    tag: '3.8'

global:
  environment: sandbox
  objectStore:
    bucketName: kdp-cloud-storage

