presto:
  workers: 2
  service:
    type: NodePort
    port: 8080
  logLevel: INFO
  environment: production
  query:
    maxMemory: 1GB
    maxMemoryPerNode: 0.5GB
    maxTotalMemoryPerNode: 0.6GB
  jvm:
    maxHeapSize: 1536M
    gcMethod:
      type: UseG1GC
      g1:
        heapRegionSize: 32M
  deploy:
    replicas: 1
    container:
      image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/presto
      tag: latest
      pullPolicy: IfNotPresent
      resources:
        limits:
          memory: 2Gi
          cpu: 2
        requests:
          memory: 2Gi
          cpu: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  ingress:
    enable: true
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /v1/cluster

metastore:
  service:
    type: ClusterIP
    port: 9083
  warehouseDir: hive-s3
  deploy:
    replicas: 1
    container:
      image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/metastore
      tag: latest
      pullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

postgres:
  enable: true
  db:
    name: metastore
    user: hive
    password: password123
  service:
    type: ClusterIP
    port: 5432
  storage:
    persist: false
    size: 5Gi
    mode: ReadWriteOnce
  deploy:
    replicas: 1
    container:
      image: postgres
      tag: 11.1-alpine
      pullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

minio:
  enable: true
  storage:
    mode: ReadWriteOnce
    size: 5Gi
  service:
    type: NodePort
    port: 9000
  deploy:
    replicas: 1
    container:
      image: minio/minio
      tag: RELEASE.2019-01-16T21-44-08Z
      pullPolicy: IfNotPresent
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  ingress:
    enable: true

hook:
  container:
    image: alpine
    tag: '3.8'

hive:
  enable: true
  service:
    type: NodePort
    port: 10000
  deploy:
    replicas: 1
    container:
      image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/hive
      tag: latest
      pullPolicy:
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  spark:
    container:
      image: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/spark
      tag: latest
      pullPolicy: IfNotPresent
    master:
      url: https://kubernetes.default.svc.cluster.local:443
    executor:
      instances: 2
      memory: 512m
      labels:
      - key: hadoop-less
        value: 'true'
    driver:
      labels:
      - key: hadoop-less
        value: 'true'
    appName: kdp
    deployMode: cluster

global:
  environment: sandbox
  objectStore:
    bucketName: kdp-cloud-storage
