{{- if .Values.postgres.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kdp.postgres.fullname" . }}
  labels:
    component: postgres
{{ include "kdp.labels" . | indent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: postgres
    name: postgres
  selector:
    component: postgres
{{ include "kdp.labels" . | indent 4 }}
{{- end }}