apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kdp.presto.fullname" . }}-coordinator
  labels:
    component: presto
    role: coordinator
{{ include "kdp.labels" . | indent 4 }}
data:
  config.properties: |
    coordinator=true
{{- if gt (int .Values.presto.workers) 0 }}
    node-scheduler.include-coordinator=false
{{- else }}
    node-scheduler.include-coordinator=true
{{- end }}
    http-server.https.enabled=true
    http-server.https.port=8443
    http-server.https.keystore.path=/etc/presto/presto.jks
    http-server.https.keystore.key=password123
    http-server.http.port={{ .Values.presto.service.port }}
    query.max-memory={{ .Values.presto.query.maxMemory }}
    query.max-memory-per-node={{ .Values.presto.query.maxMemoryPerNode }}
    query.max-total-memory-per-node={{ .Values.presto.query.maxTotalMemoryPerNode }}
    memory.heap-headroom-per-node=0.75GB
    discovery-server.enabled=true
    discovery.uri=http://{{ template "kdp.presto.fullname" . }}:{{ .Values.presto.service.port }}
