apiVersion: v1
kind: Service
metadata:
  name: {{ template "kdp.presto.fullname" . }}
  labels:
    component: presto
    role: coordinator
{{ include "kdp.labels" . | indent 4 }}
spec:
  type: {{ .Values.presto.service.type }}
  ports:
  - port: {{ .Values.presto.service.port }}
    targetPort: http-coord
    name: http-coord
  selector:
    component: presto
    role: coordinator
{{ include "kdp.labels" . | indent 4 }}
